title: Products
template: our-products/show
layout: layout
mount: 7d22fe5c-eaef-4c0c-bb32-310d2764ab32
taxonomies:
  - category
revisions: false
title_format: '{name}'
route: '{mount}/{slug}.html'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
